export type GuideSection = { id: string; title: string; paragraphs?: string[]; bullets?: string[]; steps?: string[]; rows?: [string, string][]; note?: { title: string; text: string } };
export type Guide = { lead: string; sections: GuideSection[] };

export const guides: Record<string, Guide> = {
  start: { lead: "Build useful technical projects, grow your skills, and earn equipment that helps you build what comes next.", sections: [
    { id: "program", title: "A program for technical builders", paragraphs: ["LOADOUT focuses on tools, systems, compute, and hardware. Build something that expands what you or another builder can make, run, measure, understand, or improve."] },
    { id: "loadout", title: "Your two Loadouts", rows: [["Digital Loadout", "The accepted technical projects you built."], ["Physical Loadout", "Equipment and resources that help you take on the next project."]], paragraphs: ["Build and document a project, ship it for review, earn Bolts and Track XP, then use your progress to tackle a harder build."] },
    { id: "status", title: "Joining LOADOUT", note: { title: "In development", text: "LOADOUT has not launched yet. RSVP records interest; it does not enroll you or confirm eligibility. Joining requirements, dates, and available prizes will be published before launch." } },
  ] },
  projects: { lead: "The technical work decides fit. Choose the track or tracks that match what you build.", sections: [
    { id: "fit", title: "What makes a project fit?", bullets: ["You personally do substantial technical work.", "The project expands a useful technical capability.", "You can demonstrate the result with code, hardware, measurements, journals, or a demo.", "Its technical work belongs in Tools, Systems, Compute, or Hardware."] },
    { id: "tracks", title: "The four tracks", rows: [["Tools", "CLIs, SDKs, debuggers, profilers, testing, and automation."], ["Systems", "Runtimes, databases, networking, deployment, and infrastructure."], ["Compute", "Graphics, GPUs, inference, numerical computing, and performance."], ["Hardware", "PCBs, embedded devices, robotics, FPGA work, and instruments."]] },
    { id: "examples", title: "Look for the technical core", rows: [["Strong signal", "An inference runtime, workflow CLI, custom renderer, or synchronization engine."], ["Usually not enough alone", "A copied tutorial site, basic AI chat screen, or ordinary product UI."]], paragraphs: ["A larger project may contain both eligible technical work and ordinary product work. Explain which capability you built; examples help guide you but do not guarantee approval."] },
    { id: "research", title: "Research Mode", paragraphs: ["Add Research Mode to any track when your project answers a technical question through experiments, measurements, reproductions, or investigation. Publish enough detail for another builder to reproduce the result.", "A reproducible report is intended to earn bonus Track XP. The exact bonus and review requirements will be confirmed before launch."] },
  ] },
  shipping: { lead: "Make your project usable and give another builder enough evidence to understand it.", sections: [
    { id: "steps", title: "From an idea to a ship", steps: ["Choose a technical capability to build or improve.", "Build while tracking your own work and keeping a journal.", "Ship a working result with source, a demo where useful, and clear documentation.", "Submit it for project-fit, validity, and quality review.", "Use feedback and progress to support your next build."] },
    { id: "journal", title: "Tracking and journals", paragraphs: ["Hackatime is planned for coding, and Lapse for eligible hardware and other non-code work. Complete setup instructions will be available before launch.", "Use a journal to connect tracked time to decisions, experiments, failures, and checks. Recorded time is not automatic approval; reviewers credit the eligible work they can verify."] },
    { id: "versions", title: "Shipping another version", paragraphs: ["You can ship a later version when it adds genuinely new work or capability. Explain what changed and submit only that new work. The same implementation or hours cannot be rewarded twice."] },
  ] },
  review: { lead: "Review checks whether the project fits, whether the submitted work is valid, and how strong that work is.", sections: [
    { id: "stages", title: "What reviewers check", rows: [["Project fit", "Does the technical work belong in LOADOUT?"], ["Validity", "Do the artifact, tracked time, journals, attribution, and evidence support the submission?"], ["Quality", "How strong is the approved technical work across the four dimensions?"]] },
    { id: "quality", title: "Four quality dimensions", rows: [["Originality", "What is new in your idea, implementation, constraints, or approach?"], ["Technical Depth", "What technical challenge did you solve?"], ["Execution", "Does the result work for its intended purpose?"], ["Documentation", "Can another builder understand, verify, or reproduce it?"]] },
    { id: "authorship", title: "AI use and team projects", paragraphs: ["AI assistance is allowed. Declare how you used it and show what you understand and built yourself. Final AI limits and review requirements will be published before launch.", "Each team member keeps their own tracked work and journal. You receive credit for your approved contribution, not the team's total time. Members can receive different track allocations."] },
    { id: "feedback", title: "Questions about a decision", paragraphs: ["Feedback should explain the decision and what evidence or improvements are needed. The planned appeal process will allow builders to question decisions about eligible work, hours, quality, or track allocation."] },
  ] },
  progress: { lead: "Bolts and Track XP are separate rewards from approved work.", sections: [
    { id: "balances", title: "Two kinds of progress", rows: [["Bolts", "Global, spendable currency for eligible prizes."], ["Track XP", "Unspendable lifetime progress in the fields your work demonstrates."]] },
    { id: "levels", title: "Your field levels", paragraphs: ["Each track can reach LV.15. Track XP cannot be spent, and levels persist through competitive Seasons and Community Era changes.", "Related track levels can improve prize prices or unlock some specialist equipment. Levels do not multiply the Bolts awarded for a project."] },
    { id: "work", title: "What informs an award", paragraphs: ["Approved eligible work and its quality assessment inform Bolts. Reviewers allocate Track XP to the relevant field or fields. Exact thresholds, multiplier calibration, and configured bonuses will be confirmed before launch."] },
  ] },
  prizes: { lead: "Use Bolts for eligible prizes. Related track progress can improve the price or unlock some specialist items.", sections: [
    { id: "catalog", title: "Planned prizes", paragraphs: ["The planned catalog may include developer hardware, embedded boards, compute, tools, storage, fabrication, domains, and custom equipment. Prices and availability have not been published."] },
    { id: "pricing", title: "Field discounts", paragraphs: ["Most prizes are intended to be available across tracks. A related track level can lower the Bolt price; some specialist or Mastery items may require a level.", "An ordinary discount can be capped on an expensive prize. A matching Field Requisition lets more of the discount you already earned apply to one eligible order."] },
    { id: "requisitions", title: "Field Requisitions", rows: [["LV.3 and LV.6", "Field Requisition I at each milestone."], ["LV.9 and LV.12", "Field Requisition II at each milestone."], ["LV.15", "A Master Field Requisition."]] , bullets: ["One use, non-transferable, and no expiry.", "At most one per order; it cannot add Bolts or remove a level requirement.", "The prize must meet its field and minimum-value rules.", "Exact savings allowances and minimum prices will be confirmed before launch."] },
    { id: "custom-orders", title: "Custom Orders", steps: ["Ship reviewed work and build Track XP in the relevant field.", "Reach the relevant progression tier and describe the equipment you need.", "The team checks fit, funding, availability, and delivery, then sends a final Bolt quote.", "Accept the quote if you have enough Bolts, or decline it."] , note: { title: "Not open yet", text: "Custom Order requests are not available yet. A request is not a purchase or a fulfillment promise." } },
  ] },
  eras: { lead: "Community Eras give builders a shared technical theme to explore and advance.", sections: [
    { id: "shared", title: "Shared progress", paragraphs: ["Approved projects contribute Era Points to the community. These points cannot be spent and are separate from your Track XP and Bolts.", "Optional objectives can inspire projects across the four tracks. A project still follows ordinary fit and review requirements."] },
    { id: "advance", title: "Moving to the next Era", steps: ["Approved projects add shared progress.", "An Era lasts at least 14 days and must reach its community target.", "The next Era begins at an eligible weekly reset after both conditions are met."] },
    { id: "bonus", title: "A planned project bonus", paragraphs: ["A reviewer separately checks whether a project qualifies for the active objectives. A qualifying project is planned to earn 10% of its approved base Bolt award, with no extra Track XP.", "Track levels, accepted projects, and personal balances stay with you when the Era changes."] },
    { id: "seasons", title: "Seasons are different", paragraphs: ["Seasons are competitive periods; Eras are shared technical themes. Your lifetime Track XP and accepted projects persist across both."] },
  ] },
  irl: { lead: "LOADOUT IRL is a future three-day build-weekend concept in Germany's Ruhr region.", sections: [
    { id: "weekend", title: "The proposed weekend", rows: [["Friday", "Meet builders, choose a technical project, and get started."], ["Saturday", "Build together, with room for workshops and rest."], ["Sunday", "Document, demonstrate, and share what you made."]] },
    { id: "online", title: "Part of the same LOADOUT", paragraphs: ["Event projects would use the same tracks and ordinary review as online LOADOUT. Attendance would be optional, with no separate progression advantage."] },
    { id: "status", title: "A future concept", note: { title: "Unconfirmed", text: "Dates, venue, funding, and registration are not confirmed. There is no event registration open through this site." } },
  ] },
};
